### ISSUE TITLE
Doesn't work in Joomla4 

### ISSUE THREAD

**Issue by SamusUA** [PhocaCz/PhocaGuestbook#1]
Doesn't work in Joomla4 

Frontend error:
Cannot access protected property Joomla\CMS\Menu\MenuItem::$params

Backend Error:
0 Call to undefined method Joomla\CMS\Application\ApplicationHelper::parseXMLInstallFile()

**Comment by PhocaCz** [comment]
Hi, yes, for now, there is still not Joomla 4 version, see:
https://www.phoca.cz/forum/viewtopic.php?f=7&t=62650

Jan

**Comment by SamusUA** [comment]
@PhocaCz, Thanks for the answer!
I would like to know if there will be an update and how many months to wait for it? The component is very useful, I have many sites using it. And I want to translate all these sites into J4.
Thanks in advance!

**Comment by PhocaCz** [comment]
Hi, did you read the post I have linked to? As written there, it is in my plans but I really cannot give any estimate as there are so many factors which influence it.

Jan

**Comment by SamusUA** [comment]
I understood you! Are looking forward to!
Thanks for your great job!

**Comment by PhocaCz** [comment]
Ok
