### ISSUE TITLE
Message deletion error

### ISSUE THREAD

**Issue by webarion** [PhocaCz/PhocaGuestbook#4]
On Joomla 4.3.0, when deleting a post, an error occurs:
0 Call to undefined method Joomla\Database\Mysqli\MysqliDriver::query()

**Comment by PhocaCz** [comment]
Hi, which version of Phoca Guestbook do you use? When you enable debug mode, do you get full error message (including line and file where this occurs)?

**Comment by PhocaCz** [comment]
Testing now 4.0.2, everything is OK for me :idea:

![phoca guestbook delete posts](https://i.imgur.com/Bjm0T08.png)

**Comment by webarion** [comment]
Hello! This is frontend.

![1](https://github.com/PhocaCz/PhocaGuestbook/assets/28953448/86ec6797-c06c-4fe0-a828-b234541a3486)
![2](https://github.com/PhocaCz/PhocaGuestbook/assets/28953448/5ee34f89-27ce-4920-a431-a0a51351ac14)
![3](https://github.com/PhocaCz/PhocaGuestbook/assets/28953448/ce8c10ef-99cd-44f1-8c26-10a1601cd513)

**Comment by PhocaCz** [comment]
Hi, thank you for the info, yes, confirmed, there is a problem in frontend. I will fix it in next version.

Thank you, Jan
